// Code generated by MockGen. DO NOT EDIT.
// Source: backend/backend.go
//
// Generated by this command:
//
//	mockgen -source=backend/backend.go -destination=testutil/mock_backend.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"
	time "time"

	backend "github.com/aetomala/worklease/backend"
	gomock "go.uber.org/mock/gomock"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockBackend) Acquire(ctx context.Context, workID, holderID string, ttl time.Duration) (backend.LeaseRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, workID, holderID, ttl)
	ret0, _ := ret[0].(backend.LeaseRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockBackendMockRecorder) Acquire(ctx, workID, holderID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockBackend)(nil).Acquire), ctx, workID, holderID, ttl)
}

// Checkpoint mocks base method.
func (m *MockBackend) Checkpoint(ctx context.Context, record backend.LeaseRecord, state []byte, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkpoint", ctx, record, state, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkpoint indicates an expected call of Checkpoint.
func (mr *MockBackendMockRecorder) Checkpoint(ctx, record, state, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkpoint", reflect.TypeOf((*MockBackend)(nil).Checkpoint), ctx, record, state, ttl)
}

// ReadCheckpoint mocks base method.
func (m *MockBackend) ReadCheckpoint(ctx context.Context, record backend.LeaseRecord) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCheckpoint", ctx, record)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadCheckpoint indicates an expected call of ReadCheckpoint.
func (mr *MockBackendMockRecorder) ReadCheckpoint(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCheckpoint", reflect.TypeOf((*MockBackend)(nil).ReadCheckpoint), ctx, record)
}

// Release mocks base method.
func (m *MockBackend) Release(ctx context.Context, record backend.LeaseRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockBackendMockRecorder) Release(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockBackend)(nil).Release), ctx, record)
}

// Renew mocks base method.
func (m *MockBackend) Renew(ctx context.Context, record backend.LeaseRecord, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", ctx, record, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Renew indicates an expected call of Renew.
func (mr *MockBackendMockRecorder) Renew(ctx, record, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockBackend)(nil).Renew), ctx, record, ttl)
}
