// Code generated by MockGen. DO NOT EDIT.
// Source: lease.go
//
// Generated by this command:
//
//	mockgen -source=lease.go -destination=testutil/mock_lease.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	worklease "github.com/aetomala/worklease"
	gomock "go.uber.org/mock/gomock"
)

// MockLease is a mock of Lease interface.
type MockLease struct {
	ctrl     *gomock.Controller
	recorder *MockLeaseMockRecorder
	isgomock struct{}
}

// MockLeaseMockRecorder is the mock recorder for MockLease.
type MockLeaseMockRecorder struct {
	mock *MockLease
}

// NewMockLease creates a new mock instance.
func NewMockLease(ctrl *gomock.Controller) *MockLease {
	mock := &MockLease{ctrl: ctrl}
	mock.recorder = &MockLeaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLease) EXPECT() *MockLeaseMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockLease) Acquire(ctx context.Context, workID string, opts ...worklease.AcquireOption) (worklease.Token, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Acquire", varargs...)
	ret0, _ := ret[0].(worklease.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockLeaseMockRecorder) Acquire(ctx, workID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockLease)(nil).Acquire), varargs...)
}

// Checkpoint mocks base method.
func (m *MockLease) Checkpoint(ctx context.Context, token worklease.Token, state []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkpoint", ctx, token, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkpoint indicates an expected call of Checkpoint.
func (mr *MockLeaseMockRecorder) Checkpoint(ctx, token, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkpoint", reflect.TypeOf((*MockLease)(nil).Checkpoint), ctx, token, state)
}

// ReadCheckpoint mocks base method.
func (m *MockLease) ReadCheckpoint(ctx context.Context, token worklease.Token) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCheckpoint", ctx, token)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadCheckpoint indicates an expected call of ReadCheckpoint.
func (mr *MockLeaseMockRecorder) ReadCheckpoint(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCheckpoint", reflect.TypeOf((*MockLease)(nil).ReadCheckpoint), ctx, token)
}

// Release mocks base method.
func (m *MockLease) Release(ctx context.Context, token worklease.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockLeaseMockRecorder) Release(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockLease)(nil).Release), ctx, token)
}

// Renew mocks base method.
func (m *MockLease) Renew(ctx context.Context, token worklease.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Renew indicates an expected call of Renew.
func (mr *MockLeaseMockRecorder) Renew(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockLease)(nil).Renew), ctx, token)
}

// StartRenewal mocks base method.
func (m *MockLease) StartRenewal(ctx context.Context, token worklease.Token, opts ...worklease.RenewalOption) (context.Context, func()) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, token}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartRenewal", varargs...)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// StartRenewal indicates an expected call of StartRenewal.
func (mr *MockLeaseMockRecorder) StartRenewal(ctx, token any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, token}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRenewal", reflect.TypeOf((*MockLease)(nil).StartRenewal), varargs...)
}

// MockLeaseObserver is a mock of LeaseObserver interface.
type MockLeaseObserver struct {
	ctrl     *gomock.Controller
	recorder *MockLeaseObserverMockRecorder
	isgomock struct{}
}

// MockLeaseObserverMockRecorder is the mock recorder for MockLeaseObserver.
type MockLeaseObserverMockRecorder struct {
	mock *MockLeaseObserver
}

// NewMockLeaseObserver creates a new mock instance.
func NewMockLeaseObserver(ctrl *gomock.Controller) *MockLeaseObserver {
	mock := &MockLeaseObserver{ctrl: ctrl}
	mock.recorder = &MockLeaseObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaseObserver) EXPECT() *MockLeaseObserverMockRecorder {
	return m.recorder
}

// OnAcquire mocks base method.
func (m *MockLeaseObserver) OnAcquire(ctx context.Context, e worklease.AcquireEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnAcquire", ctx, e)
}

// OnAcquire indicates an expected call of OnAcquire.
func (mr *MockLeaseObserverMockRecorder) OnAcquire(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAcquire", reflect.TypeOf((*MockLeaseObserver)(nil).OnAcquire), ctx, e)
}

// OnCheckpoint mocks base method.
func (m *MockLeaseObserver) OnCheckpoint(ctx context.Context, e worklease.CheckpointEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCheckpoint", ctx, e)
}

// OnCheckpoint indicates an expected call of OnCheckpoint.
func (mr *MockLeaseObserverMockRecorder) OnCheckpoint(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCheckpoint", reflect.TypeOf((*MockLeaseObserver)(nil).OnCheckpoint), ctx, e)
}

// OnFenced mocks base method.
func (m *MockLeaseObserver) OnFenced(ctx context.Context, e worklease.FencedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnFenced", ctx, e)
}

// OnFenced indicates an expected call of OnFenced.
func (mr *MockLeaseObserverMockRecorder) OnFenced(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnFenced", reflect.TypeOf((*MockLeaseObserver)(nil).OnFenced), ctx, e)
}

// OnReadCheckpoint mocks base method.
func (m *MockLeaseObserver) OnReadCheckpoint(ctx context.Context, e worklease.ReadCheckpointEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnReadCheckpoint", ctx, e)
}

// OnReadCheckpoint indicates an expected call of OnReadCheckpoint.
func (mr *MockLeaseObserverMockRecorder) OnReadCheckpoint(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnReadCheckpoint", reflect.TypeOf((*MockLeaseObserver)(nil).OnReadCheckpoint), ctx, e)
}

// OnRelease mocks base method.
func (m *MockLeaseObserver) OnRelease(ctx context.Context, e worklease.ReleaseEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnRelease", ctx, e)
}

// OnRelease indicates an expected call of OnRelease.
func (mr *MockLeaseObserverMockRecorder) OnRelease(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRelease", reflect.TypeOf((*MockLeaseObserver)(nil).OnRelease), ctx, e)
}

// OnRenew mocks base method.
func (m *MockLeaseObserver) OnRenew(ctx context.Context, e worklease.RenewEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnRenew", ctx, e)
}

// OnRenew indicates an expected call of OnRenew.
func (mr *MockLeaseObserverMockRecorder) OnRenew(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRenew", reflect.TypeOf((*MockLeaseObserver)(nil).OnRenew), ctx, e)
}
